<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMrhEif\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMrhEif/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGMrhEif.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGMrhEif\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGMrhEif\App_KernelDevDebugContainer([
    'container.build_hash' => 'GMrhEif',
    'container.build_id' => '48dd06d8',
    'container.build_time' => 1589410680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMrhEif');
